from __future__ import annotations

from enum import Enum


class ReasonCode(str, Enum):
    # --- Handshake / creation ---
    HANDSHAKE_OK = "HANDSHAKE_OK"
    HANDSHAKE_REJECT = "HANDSHAKE_REJECT"

    # --- Volatility signals ---
    VOLATILITY_SIGNAL = "VOLATILITY_SIGNAL"
    QUALITY_THRESHOLD_EXCEEDED = "QUALITY_THRESHOLD_EXCEEDED"

    # --- Recovery lifecycle ---
    RECOVERY_START = "RECOVERY_START"
    REATTACH_SUCCESS = "REATTACH_SUCCESS"
    REATTACH_REJECT = "REATTACH_REJECT"
    RECOVERY_BOUNDS_EXCEEDED = "RECOVERY_BOUNDS_EXCEEDED"

    # --- TTL / expiry ---
    SESSION_TTL_EXPIRED = "SESSION_TTL_EXPIRED"
    TRANSPORT_TTL_EXPIRED = "TRANSPORT_TTL_EXPIRED"

    # --- Policy / anti-flap ---
    POLICY_DENY = "POLICY_DENY"
    POLICY_FLAP_LIMIT = "POLICY_FLAP_LIMIT"
    POLICY_COOLDOWN_ACTIVE = "POLICY_COOLDOWN_ACTIVE"

    # --- Auth / security ---
    AUTH_FAIL = "AUTH_FAIL"
    FRESHNESS_INVALID = "FRESHNESS_INVALID"
    REPLAY_DETECTED = "REPLAY_DETECTED"
    SESSION_NOT_FOUND = "SESSION_NOT_FOUND"

    # --- Ownership / cluster safety ---
    OWNERSHIP_CONFLICT = "OWNERSHIP_CONFLICT"
    NOT_AUTHORITATIVE_OWNER = "NOT_AUTHORITATIVE_OWNER"

    # --- State / correctness ---
    INVARIANT_VIOLATION = "INVARIANT_VIOLATION"
    INVALID_STATE_TRANSITION = "INVALID_STATE_TRANSITION"

    # --- Operational / internal ---
    INTERNAL_ERROR = "INTERNAL_ERROR"